### ISSUE TITLE
How can I finish 114 level? (This seems impossible)

### ISSUE THREAD

**Issue by mufabil45** [dulvui/ball2box#13]
![Screenshot_20240505_125035](https://github.com/dulvui/ball2box/assets/37070857/1b127c98-a4a6-47f1-93b0-f1dce703d0aa)

That growing and shrinking peg just get in the way.

Is this a bug or an intentional feature?

**Comment by dulvui** [comment]
It is intentional, you can try with a different ball.
The orange ball should be the smallest one.

**Comment by dulvui** [comment]
Please re-open the issue, if the problem persists.
