### ISSUE TITLE
Z-fighting on level 65

### ISSUE THREAD

**Issue by myclevorname** [dulvui/ball2box#17]
On level 65, the 3 cubes are Z-fighting with the white bars. Sometimes, they are behind, and other times, they are in front of the white bars. I tried to make the blue cubes eat the ball because I thought that would make the cubes appear in front of the bars, but that may or may not be the case.

https://usercontent.irccloud-cdn.com/file/rrOGGDZ2/ball2box_65.mp4

**Comment by dulvui** [comment]
Thanks for letting me know! I'll fix the z-index problem in level 65 before releasing the next version.
I think there are also other levels where this happens, so I'll investigate a general solution or simply fix it in all affected levels.

**Comment by dulvui** [comment]
Bug fixed on version 4.1.4 for levels 65 and 67
