### ISSUE TITLE
Ball gets stuck in narrow places

### ISSUE THREAD

**Issue by slackjeff** [dulvui/ball2box#19]
The ball in the print gets stuck in narrow places and doesn't pass through any phase...
![game1x](https://github.com/user-attachments/assets/47d6aa9a-8d00-4b99-942d-0544d4526e70)

**Comment by dulvui** [comment]
Oh that's a problem, thanks for letting me know! I'll fix it with the next version, and make sure all balls are able to pass this "tunnel".
In the meantime you use a smaller ball, that should work for sure.

**Comment by dulvui** [comment]
I reduced this ball's size in v4.1.5, that should be available on all platforms soon.
Now all balls have the same size in game.
