### ISSUE TITLE
Bug: resetting ball (and level) doesn't always respawn all purple boxes

### ISSUE THREAD

**Issue by Irgendeinwer** [dulvui/ball2box#20]
The ball doesn't disappear instantly after resetting but stays alive a short while. If you hit a purple box during this period it still disappears and doesn't respawn.

https://github.com/user-attachments/assets/f198feaa-db8b-4b83-bdae-0f9d41dda493

**Comment by dulvui** [comment]
Thanks for opening the issue, I'll fix it in the next update.
