### ISSUE TITLE
The app does not start at all.

### ISSUE THREAD

**Issue by n00xbg** [dulvui/ball2box#3]
When I try to start the app - blue screen appears for a couple of seconds and the app closes.
I downloaded it from F-Droid.

Device : Huawei Y5P
![334935298_587242103450091_4763626976747001168_n](https://user-images.githubusercontent.com/127140061/223204983-ca6fa026-5ca2-41df-83ab-37307a7e6e97.jpg)

**Comment by dulvui** [comment]
The version 2.2.3 is broken and an update with the fix is already coming in the next days.
Until then, please install version 2.2.2. You can find the different version at the bottom of the App screen in the F-Droid App.

**Comment by dulvui** [comment]
The game works now again with the latest update version 2.2.6 on F-Droid.
