### ISSUE TITLE
How do you complete level 97?

### ISSUE THREAD

**Issue by jeremiah-miller** [dulvui/ball2box#4]
By the time the ball gets to the bottom, it has no momentum to bounce side to side and drops straight down to the left of the target box. I'm completely stumped on how to give it more momentum to be able to bounce into the target, any hints?

**Comment by dulvui** [comment]
It is tricky and can be frustrating, but it's possible!
Try with a really bouncy ball like Japanese ball in the video or the Brazilian ball
https://user-images.githubusercontent.com/12729238/225456549-30142789-2779-45d8-99f4-d810e1893bf2.mp4

**Comment by jeremiah-miller** [comment]
Ohh! I totally missed the shop, nice! Thanks

**Comment by dulvui** [comment]
You're welcome!
I might need to make the shop more visible or integrate it directly in the menu, so that you can change ball without having to click on the shop button. Anyway I'm working on new levels, so I'll integrate also a better shop.
