### ISSUE TITLE
Shop to choose between balls should be intergrated in the menu

### ISSUE THREAD

**Issue by dulvui** [dulvui/ball2box#5]
Many users are missing the shop and so having a difficult time to solve some levels.
The ability to change ball should be integrated directly in the menu, so that users don't have to click on the shop button.

**Comment by dulvui** [comment]
Thank you for the feedback!
I will try out different solutions and implement one. Maybe the quickest solutions would be renaming "shop" to "ball" or something similar. Long term solution: I will move the ball selection into the menu, so you can switch the ball directly there.
I might also need to change level 97 and make it a bit easier. Seems that a lot of people are stuck there.
Here the proof that it works with the Japanese ball :sweat_smile:
https://www.youtube.com/shorts/lSF-ZgUZ64g

**Comment by carwe** [comment]
i actually tested this one - not often enough, it seems. i skipped the "flag"-balls then as improbable solution, as you possibly cannot expect users to buy and test all of them, when there are not enough stars available in the lvls 1-96 to pay for all of them

**Comment by dulvui** [comment]
I renamed now the store to ball. An update for all stores on the way.
